### PR TITLE
Feature/movies list content

### PR DESCRIPTION
**Pull request by KonradBauer**
Create popular movies page, check responsiveness in mobile screens.

### CODE REVIEW

**Review by piotrpaczuski — CHANGES_REQUESTED** [review]
From 610px the tiles overlap when shrinking the width of the screen.

**Comment by KonradBauer** [comment]
I think I fix the problem, please check

**Review by florekdeveloper — APPROVED** [review]
All works fine

**Review by piotrpaczuski — APPROVED** [review]
All views looks good, well done.

**Pull request merged**
