### PR TITLE
Person details - layout

### PR DESCRIPTION
**Pull request by KonradBauer**
I create person details page, check responsiveness and look.

### CODE REVIEW

**Comment by florekdeveloper** [comment]
Mobile view ok, but on laptop when is less than 845px tile gets much smaller.

**Review by florekdeveloper — CHANGES_REQUESTED** [review]
Mobile view ok, but on laptop when is less than 845px tile gets much smaller.

**Comment by piotrpaczuski** [comment]
> Mobile view ok, but on laptop when is less than 845px tile gets much smaller.

You have on mind tile with person details?

**Review by piotrpaczuski — APPROVED** [review]
All views are correctly, tile with person details I will adapt to this view later.

**Comment by florekdeveloper** [comment]
Agree with that

**Review by florekdeveloper — APPROVED** [review]
Agreed changes will appear later

**Comment by KonradBauer** [comment]
Agree with that decision

**Pull request merged**
