### PR TITLE
Refactoring project

### PR DESCRIPTION
**Pull request by piotrpaczuski**
I working on refactoring project to our code to will be more readable and reusable. I changing all exports to default for components.

### CODE REVIEW

**Comment by florekdeveloper** [comment]
Improved very well :)

**Comment by piotrpaczuski** [comment]
I changed the export of each component to default because I wanted, to separate the import of components from the rest. Check if everything works and look at the code how I refactored our project. I checked the operation of each component after refactoring and didn't notice any problems.

**Review by KonradBauer — APPROVED** [review]
Code looks more better than before. Better code organization. Good idea to separate Content to Contents, when u separate movies and peoples logic. You pulled the logic of the dispatches above of the components, it's make the code looks better and more readable.

**Review by florekdeveloper — APPROVED** [review]
Code looks much better 🙂 great job

**Pull request merged**
