### PR TITLE
Popular people styled layout

### PR DESCRIPTION
**Pull request by KonradBauer**
Check popular people layout, check mobiles responsiveness.

### CODE REVIEW

**Review by piotrpaczuski — CHANGES_REQUESTED** [review]
From 900px to lower widths layout Tiles is repeat from higher widths. That layout doesn't view correctly in this widths on pc.

**Comment by KonradBauer** [comment]
I fix the problem, check result

**Review by florekdeveloper — APPROVED** [review]
Checked and looks like is sorted now.

**Review by piotrpaczuski — APPROVED** [review]
Now this page from 900px display correctly.

**Pull request merged**
