### PR TITLE
Layout/pagination

### PR DESCRIPTION
**Pull request by KonradBauer**
Added pagination for desktop view, check look. I add soon mobile view.

### CODE REVIEW

**Review by piotrpaczuski — COMMENTED** [review]
Looks good, I waiting for mobile view..

**Comment by florekdeveloper** [comment]
Looks ok, just waiting for mobile view to be ready.

**Comment by KonradBauer** [comment]
Added styles from mobile screens, check it out

**Review by florekdeveloper — APPROVED** [review]
Just checked mobile view, works fine. Well done :)

**Review by piotrpaczuski — APPROVED** [review]
I approve this pagination, all views looks good.

**Pull request merged**
