### PR TITLE
Fix refresh details and added peopleId and movieId in LocalStorage

### PR DESCRIPTION
**Pull request by florekdeveloper**

### CODE REVIEW

**Comment by KonradBauer** [comment]
when i try to reviev, the npm returns :

ERROR in ./src/App.js 73:39-49

export 'ButtonsBox' (imported as 'ButtonsBox') was not found in './layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)


ERROR in ./src/features/Input/index.js 58:30-41

export 'StyledInput' (imported as 'StyledInput') was not found in '../../layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)

**Comment by piotrpaczuski** [comment]
> when i try to reviev, the npm returns :
> 
> ERROR in ./src/App.js 73:39-49
> 
> export 'ButtonsBox' (imported as 'ButtonsBox') was not found in './layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)
> 
> ERROR in ./src/features/Input/index.js 58:30-41
> 
> export 'StyledInput' (imported as 'StyledInput') was not found in '../../layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)

Did you write git pull in terminal on main branch and the next on fixrefreshdetails branch? I don't had any problems with run application on this branch.

**Review by piotrpaczuski — APPROVED** [review]
Good idea to saving movie id and person id to local storage, to use this variable after refresh.

**Comment by KonradBauer** [comment]
> > when i try to reviev, the npm returns :
> > ERROR in ./src/App.js 73:39-49
> > export 'ButtonsBox' (imported as 'ButtonsBox') was not found in './layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)
> > ERROR in ./src/features/Input/index.js 58:30-41
> > export 'StyledInput' (imported as 'StyledInput') was not found in '../../layouts/Header/styled' (possible exports: Box, HeadContainer, Input, MoviesButton, PeopleButton, StyledLogo, StyledLoupe)
> 
> Did you write git pull in terminal on main branch and the next on fixrefreshdetails branch? I don't had any problems with run application on this branch.

Yes, i did this now, and the problem still exist.

**Review by KonradBauer — APPROVED** [review]
Refresh on movieDetails and peopleDetails now works well

**Pull request merged**
