### PR TITLE
Layout/big poster

### PR DESCRIPTION
**Pull request by KonradBauer**
I make the Poster component. Any ideas to make shadow be top of the poster?

### CODE REVIEW

**Comment by piotrpaczuski** [comment]
Look on this, here you have all possible ways: https://codepen.io/eyecatchup/pen/wLZgMJ

**Comment by KonradBauer** [comment]
Yeah, but my problem is why image is on top of the shadow. I want to make shadow overlay layer be top of the image.

**Review by florekdeveloper — APPROVED** [review]
Looks good

**Review by piotrpaczuski — APPROVED** [review]
Overlook is good

**Pull request merged**
