### PR TITLE
Layout/header

### PR DESCRIPTION
**Pull request by KonradBauer**
Finished Header layout, to be checked :)

Check the responsiveness on mobile devices. I created the component in the main directory, when the structure is created, it will have to be moved.

### CODE REVIEW

**Comment by piotrpaczuski** [comment]
Well done, but it will be better if we write the max widths which we use in media queries in the theme as "breakpoints", because we use them in many places. In widths from 1500px to 1920px, the header does not adapt to the screen.

**Comment by florekdeveloper** [comment]
Great job, agree with Piotr about max width.

**Review by florekdeveloper — APPROVED** [review]
Looks good for me.

**Review by piotrpaczuski — APPROVED** [review]
Looks good for me too.

**Pull request merged**
