### PR TITLE
Movie details layout on screens

### PR DESCRIPTION
**Pull request by KonradBauer**
Check movie details view and check mobiles responsiveness.

### CODE REVIEW

**Review by piotrpaczuski — CHANGES_REQUESTED** [review]
Rate and votes on background poster is bad set on mobile and on standar zoom text and raiting are move to left.

**Comment by KonradBauer** [comment]
I fix the problem, now I must only move the MainInfo container lower on some screen widths

**Review by florekdeveloper — APPROVED** [review]
Looks great, just few improvements left

**Review by piotrpaczuski — APPROVED** [review]
After the change everything shows correctly, we are waiting for the improvement of details and shadow.

**Pull request merged**
