### PR TITLE
created template Tile with a few params

### PR DESCRIPTION
**Pull request by piotrpaczuski**
Code which I added to html and *, ::after, ::before in GlobalStyle must be, because without them tile doesn't show correctly. This tile isn't finished, because i must add more params to able can will be flexible.

### CODE REVIEW

**Review by KonradBauer — APPROVED** [review]
Good job, we waiting for full responsible component.

**Review by KonradBauer — APPROVED** [review]

**Review by florekdeveloper — APPROVED** [review]
All good :)

**Comment by piotrpaczuski** [comment]
I added view Tile for mobiles and noPoster image while source image is missing.

**Comment by piotrpaczuski** [comment]
Tomorrow I will create structure files for this component.

**Comment by piotrpaczuski** [comment]
I finished this component for all views. I'm waiting for your review. Check mobile view.

**Review by KonradBauer — CHANGES_REQUESTED** [review]
I checked all mobile views. The tile look's good on all screen's width to 320px, but in lower screens like **Galaxy Fold (280px) background resizes to lower than tile.** You should fix this problem.

**Comment by piotrpaczuski** [comment]
I **fixed** problem with the view on smaller screen width like **Galaxy Fold**.

**Review by KonradBauer — COMMENTED** [review]
Now mobile look is fine, You can merge 👍

**Review by KonradBauer — APPROVED** [review]

**Review by florekdeveloper — APPROVED** [review]
All ok

**Pull request merged**
